---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cuprumbe/public_html/
    - /bin/source /home/cuprumbe/virtualenv/cuprumberry/3.8/bin/activate
    - /bin/cd /home/cuprumbe/cuprumberry
    - pip install -r requirements.txt
    - python manage.py migrate
    - /bin/rm -Rf $DEPLOYPATH/static
    - python manage.py collectstatic
    - /bin/mv -v static_files/ $DEPLOYPATH/static
    - /bin/cp -ar media/ $DEPLOYPATH/media
    - /bin/selectorctl --interpreter ruby --user cuprumbe --domain cuprumberry.by --restart-webapp cuprumberry
