---
deployment:
  tasks:
    - export PYTHONPATH=/home/cuprumbe/virtualenv/cuprumberry/3.8/bin
    - export DEPLOYPATH=/home/cuprumbe/public_html/
    - export SOURCEPATH=/home/cuprumbe/cuprumberry/
    - $PYTHONPATH/pip install -r $SOURCEPATH/requirements.txt
    - $PYTHONPATH/python $SOURCEPATH/manage.py migrate
    - /bin/rm -Rf $DEPLOYPATH/static
    - $PYTHONPATH/python $SOURCEPATH/manage.py collectstatic
    - /bin/mv -v $SOURCEPATH/static_files/ $DEPLOYPATH/static
    - /bin/cp -ar $SOURCEPATH/media/ $DEPLOYPATH/media
#    - /bin/selectorctl --interpreter ruby --user cuprumbe --domain cuprumberry.by --restart-webapp cuprumberry
